exec-once = waybar --config ~/.config/waybar/config.jsonrc --style ~/.config/waybar/waybar.css
exec-once = hyprpaper 
exec-once = hypridle
exec-once = mako
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once=/usr/lib/polkit-kde-authentication-agent-1

